trigger:
- main  # Runs pipeline on every push to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Configuring Git..."
    git config --global user.email "anuragsinghsisodiya27@gmail.com"
    git config --global user.name "AnuragSisodiya27"

    echo "Cloning the repository..."
    git clone https://$(GITHUB_TOKEN)@github.com/AnuragSisodiya27/Static-Website-Furniture.git repo
    cd repo

    echo "Ensuring gh-pages branch exists..."
    git checkout gh-pages || git checkout -b gh-pages

    echo "Removing old files..."
    git rm -rf .

    echo "Copying static website files..."
    cp -r $(Build.SourcesDirectory)/* .

    echo "Committing and pushing to GitHub Pages..."
    git add .
    git commit -m "Automated deployment from Azure DevOps"
    git push --set-upstream origin gh-pages --force
  displayName: 'Deploy Static Website to GitHub Pages'
